=== EduardoJaraRodriguez/Tercer-corte/estudiante XML DTD/bin/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">

    <complexType name="Estudiante">
    	<sequence>
    		<element name="Codigo" type="string"></element>
    		<element name="Nombre" type="string"></element>
    		<element name="Semestre" type="tns:Semestre" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    

    <complexType name="Curso">
    	<sequence>
            <element name="Nombre" type="string"></element>
            <element name="Codigo" type="string"></element>
            <element name="Nota_1" type="double"></element>
    		<element name="Nota_2" type="double"></element>
    		<element name="Nota_3" type="double"></element>
    		<element name="Nota_Final" type="double"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Semestre">
    	<sequence>
    		<element name="Numero" type="string"></element>
    		<element name="curso" type="tns:Curso" maxOccurs="7"></element>
    	</sequence>
    </complexType>
    



    <complexType name="Estudiantes">
    	<sequence>
    		<element name="estudiante" type="tns:Estudiante" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="estudiantes" type="tns:Estudiantes"></element>
</schema>

=== EduardoJaraRodriguez/Tercer-corte/NewXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:estudiante xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd ">
  <tns:Codigo>102509</tns:Codigo>
  <tns:Nombre>tns:Eduardo</tns:Nombre>
  <tns:Semestre>
    <tns:Numero>8</tns:Numero>
    <tns:curso>
      <tns:Nombre>aplicaciones</tns:Nombre>
      <tns:Codigo>NA1043</tns:Codigo>
      <tns:Nota_1>5.0</tns:Nota_1>
      <tns:Nota_2>5.0</tns:Nota_2>
      <tns:Nota_3>5.0</tns:Nota_3>
      <tns:Nota_Final>5.0</tns:Nota_Final>
    </tns:curso>
    <tns:curso>
      <tns:Nombre>calculo III</tns:Nombre>
      <tns:Codigo>NA1345</tns:Codigo>
      <tns:Nota_1>4.0</tns:Nota_1>
      <tns:Nota_2>4.0</tns:Nota_2>
      <tns:Nota_3>3.8</tns:Nota_3>
      <tns:Nota_Final>4.0</tns:Nota_Final>
    </tns:curso><tns:curso>
      <tns:Nombre>programacion I</tns:Nombre>
      <tns:Codigo>NA1245</tns:Codigo>
      <tns:Nota_1>1.0</tns:Nota_1>
      <tns:Nota_2>1.0</tns:Nota_2>
      <tns:Nota_3>1.0</tns:Nota_3>
      <tns:Nota_Final>1.0</tns:Nota_Final>
    </tns:curso><tns:curso>
      <tns:Nombre>fundamentos</tns:Nombre>
      <tns:Codigo>NA0987</tns:Codigo>
      <tns:Nota_1>5.0</tns:Nota_1>
      <tns:Nota_2>5.0</tns:Nota_2>
      <tns:Nota_3>5.0</tns:Nota_3>
      <tns:Nota_Final>5.0</tns:Nota_Final>
    </tns:curso><tns:curso>
      <tns:Nombre>Investigacion</tns:Nombre>
      <tns:Codigo>NA8759</tns:Codigo>
      <tns:Nota_1>5.0</tns:Nota_1>
      <tns:Nota_2>5.0</tns:Nota_2>
      <tns:Nota_3>5.0</tns:Nota_3>
      <tns:Nota_Final>5.0</tns:Nota_Final>
    </tns:curso>
  </tns:Semestre>
</tns:estudiante>

=== EduardoJaraRodriguez/Tercer-corte/estudiante XML DTD/bin/NewXMLSchema1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:estudiantes xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd ">
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
  <tns:estudiante>
    <tns:Codigo>tns:Codigo</tns:Codigo>
    <tns:Nombre>tns:Nombre</tns:Nombre>
    <tns:Semestre>
      <tns:Numero>tns:Numero</tns:Numero>
      <tns:curso>
        <tns:Nombre>tns:Nombre</tns:Nombre>
        <tns:Codigo>tns:Codigo</tns:Codigo>
        <tns:Nota_1>0.0</tns:Nota_1>
        <tns:Nota_2>0.0</tns:Nota_2>
        <tns:Nota_3>0.0</tns:Nota_3>
        <tns:Nota_Final>0.0</tns:Nota_Final>
      </tns:curso>
    </tns:Semestre>
  </tns:estudiante>
</tns:estudiantes>
